CREATE TABLE SCHOOL
(
    ID         BIGSERIAL PRIMARY KEY,
    NAME       VARCHAR(255)   NOT NULL,
    HOUR_PRICE NUMERIC(20, 2) NOT NULL
);

CREATE TABLE PARENT
(
    ID         BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL
);

CREATE TABLE CHILD
(
    ID         BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    PARENT_ID  BIGSERIAL,
    SCHOOL_ID  BIGSERIAL,
    FOREIGN KEY (PARENT_ID) REFERENCES PARENT (ID),
    FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL (ID)
);

CREATE TABLE ATTENDANCE
(
    ID         BIGSERIAL PRIMARY KEY,
    CHILD_ID   BIGSERIAL,
    ENTRY_DATE TIMESTAMP NOT NULL,
    EXIT_DATE  TIMESTAMP NOT NULL,
    FOREIGN KEY (CHILD_ID) REFERENCES CHILD (ID)
);

CREATE INDEX idx_child_school_id
    ON CHILD (SCHOOL_ID);

CREATE INDEX idx_child_parent_id
    ON CHILD (PARENT_ID);
